### ISSUE TITLE
Fix multiple players disconnecting at once

### ISSUE THREAD

**Issue by wsowens** [ufosc/MuddySwamp#9]
```
2018-06-21 01:01:28,469 [root] [INFO] Player 7 left
Traceback (most recent call last):
  File "MuddySwamp.py", line 194, in <module>
    mud.send_message_to_all("%s quit the game" % players[event.id]["name"])
  File "/home/pi/MUD/MuddySwamp/mudserver.py", line 222, in send_message_to_all
    for client in self._clients:
RuntimeError: dictionary changed size during iteration
```

**Comment by wsowens** [comment]
This bug has been identified and fixed on the `fix-charnames` branch, a branch that will be merged shortly. 

The reason this error occurred was because sending a message to a client could cause a disconnect if the socket has been closed. This would remove the client from self._clients, causing the issue above.
